baseURL = "https://www.takameron.info/"
title = "ぶっち・ブログ"
languageCode = "ja-JP"
defaultContentLanguage = "ja"
hasCJKLanguage = true
pygmentsUseClasses = true
pygmentsCodefences = true
theme = "smartblog"

ignoreErrors = ["error-remote-getjson"]
timeout = 300000

[services]
  [services.googleAnalytics]
    ID = 'G-82B70P3QSV'

[privacy]
  [privacy.googleAnalytics]
    disable = false
    respectDoNotTrack = false

[params]
  title = "ぶっち・ブログ" # For OGP
  copyright = "© ぶっち・ブログ 2018<br>Text is available under the <a href=\"https://creativecommons.org/licenses/by/4.0/\" target=\"_blank\" rel=\"noopener noreferrer\">CC BY 4.0</a>.<br>SourceCode is licensed under the <a href=\"https://creativecommons.org/publicdomain/zero/1.0/\" target=\"_blank\" rel=\"noopener noreferrer\">CC0</a>."
  description = "日常やプログラミングなど、趣味や興味のあることを書き連ねています"
  logo = "/img/logo.png"
  quicklink = true

  [params.author]
    logo = "/img/author.png"
    name = "たかめろん"
    description= "自由気ままに書いていきます。"
    email = "contact@takameron.info"
    twitter = "takameron_info"
    #facebook = "author_facebook"
    #instagram = "author_instagram"
    github = "takameron"

[params.color]
  [params.color.light]
    base = "#FFF"
    text = "#333"
    primary = "black"
    secondary = "#5989cf"
    headerfooter = "white"
    link = "blue"

  [params.color.dark]
    base = "#333"
    text = "#e4e4e4"
    primary = "black"
    secondary = "#5989cf"
    headerfooter = "white"
    link = "#3495eb"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    guessSyntax = true
    linenos = true

[related]
  includeNewer = true
  threshold = 80
  toLower = true

  [[related.indices]]
    name = "tags"
    weight = 80

  [[related.indices]]
    name = "categories"
    weight = 50

[outputs]
  page = ["HTML", "AMP"]
